is_unbiased : 1

var_mu: 10.0
var_muprime: 20.0
var_q: 1
var_qdot: 1

k_a: 400

k_i : 0.01
k_mu : 51.6

k_p0 : 20
k_p1 : 18
k_p2 : 15
k_p3 : 10
k_p4 : 5
k_p5 : 3
k_p6 : 1 

k_d0 : 16
k_d1 : 15
k_d2 : 12
k_d3 : 6
k_d4 : 3
k_d5 : 3
k_d6 : 1

max_i : 0.5
